#!/usr/bin/env python3
from os import system
from sys import argv
interpreter = "/usr/bin/python3"

mode = argv[1] if len(argv) == 2 else 0
system("%s /home/asger/Desktop/latex-utilities/latexer/main.pyw %s" % (interpreter, mode))

