#!python3
from os import system
from sys import argv
from _environment import interpreter

mode = argv[1] if len(argv) == 2 else 0
system("%s /home/asger/Desktop/EndLosung/latexer/main.pyw %s" % (interpreter, mode))

