#!/usr/bin/env python3

from os import system
from pathlib import Path
from sys import argv

home = str(Path.home())
system("%s ~/Nextcloud/Programmering/Python/genveje/genveje.py %s" % ("python3", " ".join(argv)))

